title: Trambotic Lemons
logo: /assets/img/logo.png
description: We're Luca, Marcos, Demi and Andrea. Our car is Limonata. ğŸš™ ğŸï¸ Getting ready for Mongol Rally Poles of Inconvenience 2022
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme